---
- name: Check if NFQUEUE rule exists in DOCKER-USER chain
  ansible.builtin.command:
    cmd: iptables -t filter -C DOCKER-USER -j NFQUEUE --queue-num 1 --queue-bypass
  register: lab_1_suricata_ips_nfqueue_rule_check
  failed_when: false
  changed_when: false
  tags: [iptables]

- name: Remove existing NFQUEUE rules from DOCKER-USER chain
  ansible.builtin.command:
    cmd: iptables -t filter -D DOCKER-USER -j NFQUEUE --queue-num 1 --queue-bypass
  when: lab_1_suricata_ips_nfqueue_rule_check.rc == 0
  changed_when: lab_1_suricata_ips_nfqueue_rule_check.rc == 0
  tags: [iptables]

- name: Add NFQUEUE rule for Docker traffic
  ansible.builtin.command:
    cmd: "iptables -I DOCKER-USER -j NFQUEUE --queue-num 1 --queue-bypass"
  changed_when: true
  tags: [iptables]

- name: Save iptables rules persistently
  ansible.builtin.command:
    cmd: netfilter-persistent save
  changed_when: true
  tags: [iptables]
